default:
  database:
    host: localhost
    database: postgres
    username: LINKING
    password: LINKING
    type: postgresql
    dialect: postgres
development:
  database:
    host: localhost
    database: postgres
    username: LINKING
    password: LINKING
    type: postgresql
    dialect: postgres
