default:
  database:
    host: localhost
    database: angular-init
    username: svandecappelle
    password:
    type: postgresql
    dialect: postgres
    dialectOptions:
      multipleStatements: true
  port: 3000
development:
  database:
    host: localhost
    database: angular-init
    username: svandecappelle
    password:
    type: postgresql
    dialect: postgres
    dialectOptions:
      multipleStatements: true
  port: 3000
