default:
  database:
    host: localhost
    database: angular-init
    username: svandecappelle
    password:
    type: postgresql
    dialect: postgres
development:
  database:
    host: localhost
    database: angular-init
    username: svandecappelle
    password:
    type: postgresql
    dialect: postgres
